compatibility_date = "2023-05-18"
name = "hilldrive-rideshare"
pages_build_output_dir = "dist"

[build]
command = "npm run build"
publish = "dist"

[build.environment]
NODE_VERSION = "18.17.0"

[preview]
command = "npm run preview"